title: Junior World
iconURL: assets/Dobby.jpeg
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: seonaa

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 3290
google_analytics: UA-NNNNNNNN-N